### ISSUE TITLE
Example error on batch file

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#186]
Following [your instructions](https://github.com/SimonBiggs/scriptedforms/tree/master/example) I am able to run `start example` from anywhere, but when I place in a batch file I get the following error:

![image](https://user-images.githubusercontent.com/11855322/37961896-6cf077c2-31b1-11e8-93e4-3e16d5289594.png)

**Comment by SimonBiggs** [comment]
did you run "pip install -e ."?

**Comment by SimonBiggs** [comment]
Actually scratch that. Can you download the most recent repo. I have made it so that the example should still work even if the path isn't properly set (which appears to be the issue in your case).

There is an extra file within the example package `__main__.py`, and the command is now instead `start python -m example`. That way python is used to find the package and the Windows path is not relied upon.

**Comment by robmarkcole** [comment]
OK the updated version runs fine from the command line but from the .bat I get:

![image](https://user-images.githubusercontent.com/11855322/37969825-b3ece116-31c9-11e8-922e-81235ebee6a7.png)

I have had problems with python not being on my office PC PATH before and have numerous issues with admin rights so my office PC might be a special case. I will try on a lab PC where I have full admin rights.

**Comment by SimonBiggs** [comment]
Okay for me to close this issue?
