### ISSUE TITLE
Configurable form usable area 

### ISSUE THREAD

**Issue by OxygenLithium** [SimonBiggs/scriptedforms#242]
Would it be possible for the usable area in a form to be configurable?
Or is this something that is fixed by Jupyter itself?

I'm thinking about the possibility of displaying large images or multiple elements next to each other.
E.g. an image next to a table

**Comment by SimonBiggs** [comment]
Usable area? When you say large images do you mean plots?

**Comment by OxygenLithium** [comment]
Yes plots (images displayed in matplotlib figures etc.)

But I meant in general, is there some way to use this space?

![usablearea](https://user-images.githubusercontent.com/36341776/38858383-8c92dfac-4223-11e8-9fd0-1bc61b3cd2b3.PNG)

**Comment by SimonBiggs** [comment]
It's not a limitation from Jupyter. Really the sky's the limit on the flexibility of what can be done. That space looks like that because of design choices I have made.

How are your html + css skills? Standard html can be written into the scriptedform markdown file. And style tags are allowed. You should have quite a bit of flexibility in altering the layout with CSS and HTML alone.

From hearing requests from yourself and Robin it is making me think it might be worth making the ability to have a "page layout" file. Which can be a simpler way to control all sorts of things on the page...

I'm not sure though. If I was to go down that path I'd need to think long and hard about what would be implemented...

**Comment by OxygenLithium** [comment]
My html + css skills are fairly limited but I can definitely give it a go. I understand the design choices, it looks good and 'material design'-esque but does also pose limitations. Perhaps it is best leaving it as is for now, with more advanced formatting changes left to those that want to mess with the HTML?

**Comment by OxygenLithium** [comment]
Though in the long term a page layout file does sound very nice. Perhaps just the ability to place buttons/tables 'in-line' would be good in the short term?

**Comment by SimonBiggs** [comment]
I'm not at a computer to try it out, but does the following work:

```
<span style="width:50%">
Table here
</span>
<span style="width:50%">
Code that gives output here
</span>
```

**Comment by SimonBiggs** [comment]
And I don't think this bit will work... But it might. If you write the following:

```
<style>
  .scripted-form-widget .form-contents {
    max-width: none !important;
  }
</style>
```

**Comment by SimonBiggs** [comment]
That might remove the columns from the side... But I'm not sure if you can access that styling from the form...

**Comment by OxygenLithium** [comment]
Does html always have to go around the sections? Whenever I try to put it inside I get 'Template parse error' 'Unexpected closing tag'. The span style didn't seem to change anything

**Comment by SimonBiggs** [comment]
I think I'll have to sit down at a computer and see what I can achieve. I'll let you know how I go when I get a chance.

**Comment by SimonBiggs** [comment]
As of `0.9.2dev2` this is now possible by writing the following at the top of the form:

```html
<style>
  .scripted-form-widget .form-contents {
    max-width: none;
  }
</style>
```
